import "./globals.css";
import AppLayout from "./AppLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta name="color-scheme" content="dark" />
      <body>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
